# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47cf81fce6cd0fd13c0ce44387e6cc0fbb2e64fd146f736e28a2422b4ad3404f53e49054eece5c51a1b98aeb40c4b638a0d753b3a26fa2a6b072877698b251c

test:
  secret_key_base: 781caaa8c272b9fbbb2fa4bf4989eefc7c46b295c81bc5dd429ae2a5765b31fb81575017a6dd22b12bef6b98e74ee2d443283a5a82e240a11cbaefb0aa0e2975

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
